import smtplib
from email.message import EmailMessage
from config import *

def send_alert(
    case_id,
    ip,
    user,
    severity,
    risk,
    intel_reason,
    malware_flag,
    vt_flag,
    correlation_reason
):
    if not ENABLE_EMAIL:
        return

    subject = f"[SOAR ALERT] {risk} | Case {case_id[:8]}"

    body = f"""
===============================
🚨 SECURITY INCIDENT ALERT
===============================

📌 Case ID        : {case_id}
🕒 Time (UTC)     : {__import__('datetime').datetime.utcnow().isoformat()}

-------------------------------
🔍 ALERT DETAILS
-------------------------------
• Severity Level : {severity}
• Risk Level     : {risk}
• Source IP      : {ip}
• Username       : {user or 'N/A'}

-------------------------------
🌍 THREAT INTELLIGENCE
-------------------------------
• Reputation     : {intel_reason}

-------------------------------
☣️ MALWARE ANALYSIS
-------------------------------
• Malware Found  : {"YES" if malware_flag else "NO"}
• VirusTotal Hit : {"YES" if vt_flag else "NO"}

-------------------------------
🔗 CORRELATION / APT CONTEXT
-------------------------------
• Attack Pattern : {correlation_reason or "Single-stage / Unknown"}

-------------------------------
🤖 SOAR MODE
-------------------------------
• Response Mode  : {RESPONSE_MODE}
• Auto Block     : {"YES" if risk == AUTO_BLOCK_RISK else "NO"}

-------------------------------
🛡️ STATUS
-------------------------------
• Case Status    : OPEN
• Action Taken   : {"Automatic containment initiated" if risk == AUTO_BLOCK_RISK else "Monitoring / Analyst review"}

===============================
This alert was generated by
Mini-SOAR (Wazuh + TI + Automation)
===============================
"""

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = EMAIL_SENDER
    msg["To"] = EMAIL_RECEIVER
    msg.set_content(body)

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=10) as s:
            s.starttls()
            s.login(EMAIL_SENDER, EMAIL_PASSWORD)
            s.send_message(msg)
            print("[MAIL] Detailed SOC alert sent")

    except Exception as e:
        print("[MAIL ERROR]", e)
